Задание на повторение материала

In [1]:
import numpy as np

1

In [5]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2

In [12]:
print(a.reshape(3, 4))
print(a.reshape(4, 3))
print(a.reshape(2, 6))
print(a.reshape(6, 2))
print(a.reshape(1, 12))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


3

print(a.reshape(-1, 3))
print(a.reshape(-1, 4))
print(a.reshape(-1, 6))
print(a.reshape(6, -1))
print(a.reshape(12, -1))

4 Нет

5

In [18]:
b = np.random.rand(3, 4)
print(b)

[[0.15554994 0.03367206 0.86002722 0.92452184]
 [0.69159616 0.85317014 0.9691053  0.17400165]
 [0.40665691 0.98830925 0.25896358 0.21764969]]


In [19]:
c = b.flatten()
print(c)

[0.15554994 0.03367206 0.86002722 0.92452184 0.69159616 0.85317014
 0.9691053  0.17400165 0.40665691 0.98830925 0.25896358 0.21764969]


6

In [23]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7

In [24]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


Между массивом а и b нет разницы

8

In [25]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
v = np.vstack((a, b))
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
10


9

In [32]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(B.size)

16


In [33]:
d = np.linalg.det(B)
d

0.0

Для матрицы B нельзя вычислить обратную мтрицу, так как определителдь равен 0

10

In [34]:
np.random.seed(42)

11

In [70]:
c = np.random.randint(1, 16, 16)
c

array([ 3,  1,  8,  3,  3,  1, 11,  5, 10,  7, 10,  9, 12,  7,  9,  8])

12

In [75]:
C = c.reshape((4,4))
C = C * 10
D = B + C
d = np.linalg.det(D)
d

-3793200.000000008

In [76]:
r = np.linalg.matrix_rank(D)
r

4

In [77]:
D_inv = D.T
D_inv

array([[ 35,  44, 123, 152],
       [ 24,  60, 156, 192],
       [103, 196, 249, 302],
       [ 62, 172, 302, 382]])